from sast.orchestrator import run_security_checks
from sast.intelligence import build_finding_entities


def main():
    # -------------------------
    # EXECUTION
    # -------------------------
    result = run_security_checks({
        "run_id": "intelligence-test",
        "repo_path": ".",
        "languages": ["python"],
        "dast": {
            "target_url": "https://example.com"
        },
        "enable_sca": True,   # toggle as needed
    })

    findings = result["findings"]

    print("\n========== EXECUTION OUTPUT ==========")
    print("TOOLS RUN:", result["tools"])
    print("RAW FINDINGS:", len(findings))

    if findings:
        print("FINDING TYPE:", type(findings[0]))

    # -------------------------
    # INTELLIGENCE
    # -------------------------
    entities = build_finding_entities(findings)

    print("\n========== INTELLIGENCE OUTPUT ==========")
    print("TOTAL ENTITIES:", len(entities))
    print("=" * 70)

    for idx, e in enumerate(entities, start=1):
        print(f"\nENTITY #{idx}")
        print("-" * 70)

        # ---- Identity ----
        print("ENTITY ID:", e.entity_id)
        print("TITLE:", e.title)
        print("WEAKNESS:", e.weakness)
        print("CATEGORY:", e.category)

        # ---- Risk ----
        print("SEVERITY:", e.severity)
        print("CONFIDENCE:", e.confidence)
        print("EXPLOITABILITY:", e.exploitability)
        print("RISK SCORE:", e.risk_score)
        print("SLA (days):", e.sla_days)

        # ---- Lifecycle ----
        print("FIRST SEEN:", e.first_seen)
        print("LAST SEEN:", e.last_seen)
        print("TIMES SEEN:", e.times_seen)
        print("RESURFACED:", e.resurfaced)

        # ---- Evidence ----
        print("\nSIGNALS:", len(e.signals))
        for s in e.signals:
            print("  - TOOL:", s.tool)
            print("    CATEGORY:", s.category)
            print("    RULE:", s.rule_id)
            print("    FILE / TARGET:", s.file)
            print("    SEVERITY:", s.severity)
            print("    CONFIDENCE:", s.confidence)
            print("    EVIDENCE:", s.evidence)

        # ---- Remediation (future AI layer) ----
        print("\nREMEDIATION:")
        print("  (placeholder)")
        print("  This will be generated by AI / rule engine later.")

        # ---- Ticketing (future integration layer) ----
        print("\nTICKET:")
        print("  (not created)")
        print("  Jira / GitHub / Linear integration pending.")

        print("=" * 70)

    print("\n========== TEST COMPLETE ==========\n")


if __name__ == "__main__":
    main()
